image:
  file: Dockerfile

# Add extensions here
#vscode:
#  extensions:
#    - Add extensions here

# exposed ports
ports:
- port: 3000
  onOpen: open-preview
# start up tasks
tasks:
- init: npm install
- command: npm start:dev
- command: mongod
